name: Discord Release Notifier
description: Send a notification to Discord when a new release is published.

inputs:
  webhook_url:
    description: "Discord Webhook URL"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set env
      run: echo "RELEASE_BODY=$(echo "${{ github.event.release.body }}" | sed -z 's/\n/\\n/g; s/..$//')" >> $GITHUB_ENV
      shell: bash
    - name: Send Discord Notification
      shell: bash
      run: |
        curl -H "Content-Type: application/json" \
          -d '{
            "content": "# [${{github.repository}}](<https://github.com/${{github.repository}}>) ${{ github.event.release.tag_name}}\n\n'"$RELEASE_BODY"'"
          }' \
          ${{inputs.webhook_url}}
      env:
        RELEASE_BODY:
